profiles/polkit-default-privs.easy
profiles/polkit-default-privs.restrictive
profiles/polkit-default-privs.standard

The necessary changes to fix the issues found in [bsc#1175633](https://bugzilla.suse.com/show_bug.cgi?id=1175633) (AUDIT-TRACKER: kdenetwork-filesharing) are [fixed in OBS](https://build.opensuse.org/package/rdiff/KDE:Unstable:Applications/kdenetwork-filesharing?linkrev=base&rev=80).

profiles: add kdenetwork-filesharing (bsc#1175633)

---

profiles/polkit-default-privs.standard

Our standard profile was less strict than upstream. 
> org.kde.filesharing.samba.isuserknown
> I: [polkit-action-origin] action is defined in policy /usr/share/polkit-1/actions/org.kde.filesharing.samba.policy shipped in rpm kdenetwork-filesharing-21.04.2-1.1.x86_64.rpm from package kdenetwork-filesharing
> W: [profile-auth-weaker-than-upstream] profile standard: setting yes:yes:yes is weaker than upstream setting no:yes:yes
The setting `yes:yes:yes` was chosen consciously because there is no obvious harm in letting unprivileged users test if a user name exists on the local system, IMHO. However there is no downside to conforming with upstream either.

kdenetwork-filesharing: align with upstream

---

profiles/polkit-default-privs.restrictive

This was relaxed via commit 8c4cbc5, bsc#850807. The enroll action was a
bit unclear back than. Let's keep it in sync with upstream at least for
the restrictive profile.

fprint.device.enroll: keep restrictive profile in sync with upstream

---

etc/polkit-rules-whitelist.json

`50-default.rules` is about to be moved to a new location. The contents remains unchanged.
Reference: https://build.opensuse.org/request/show/905083
> Wed Jul  7 08:15:04 UTC 2021 - Stefan Schubert <schubi@suse.com>
> 
> - Move /etc/polkit-1/rules.d/50-default.rules to /usr/share/polkit-1/rules.d/50-default.rules. The first location is only for admin changes.

50-default.rules: move to /usr (contents unchanged)

---

profiles/polkit-default-privs.restrictive

The standard profile should not be more strict than the restrictive profile.
>org.kde.filesharing.samba.isuserknown
>I: [polkit-action-origin] action is defined in policy /usr/share/polkit-1/actions/org.kde.filesharing.samba.policy shipped in rpm kdenetwork-filesharing-21.04.3-1.1.x86_64.rpm from package kdenetwork-filesharing
>W: [profiles-inconsistent-auth-requirements] 'any' setting in profile standard has stronger auth type (no) than profile restrictive (auth_admin_keep)
>W: [profiles-inconsistent-auth-requirements] 'any' setting in profile standard has stronger auth type (no) than profile restrictive (auth_admin_keep)

kdenetwork-filesharing: tighten the restrictive profile

---

etc/polkit-rules-whitelist.json
profiles/polkit-default-privs.easy
profiles/polkit-default-privs.restrictive
profiles/polkit-default-privs.standard

The format of etc/polkit-rules-whitelist.json changed on the master branch and it is unclear if we will need to migrate to the new format (this will only become necessary if rpmlint-checks from Factory are also backported). Leaving the old format for the moment.

whitelisting of GNOME malcontent parental controls (bsc#1177974)

---

profiles/polkit-default-privs.easy
profiles/polkit-default-privs.restrictive
profiles/polkit-default-privs.standard

This package has already been audited and whitelisted (bsc#1176742). While I was at it, I took the time and proofread the recent update from `plasma-disks-5.23.5` to `plasma-disks-5.23.90`. All changes are negligible and don't affect the privileged behavior. OK.

Backport KDE plasma5-disks (bsc#1195491)

---

src/chkstat-polkit

When debug variable is set to true in file /etc/polkit-1/rules.d/90-default-privs.rules, if polkit daemon is running without the 
```--no-debug``` 
option, the process exits logging
```"Failed with result 'core-dump'."```
This is caused by the line
```javascript
polkit.log(subject);
```
that I suppose is not using subject as a String
Changing the line to
```javascript
polkit.log("subject=" + subject);
```
fixes the problem
I think that also other versions are affected

Fix generation of file /etc/polkit-1/rules.d/90-default-privs.rules

---

profiles/polkit-default-privs.easy
profiles/polkit-default-privs.restrictive
profiles/polkit-default-privs.standard

LGTM. For completeness' sake I diffed the source of dde-api since the last proper audit, and there weren't any signifcant changes.

Backport of deepin-api whitelisting (bsc#1196681 bsc#1070943)

---

profiles/easy
profiles/restrictive
profiles/standard

gconf2 has recently been dropped from Factory via OBS sr#965379.
These actions are reported as no longer packaged by our checker scripts.
This report is correct. Therefore drop the now outdated entries.

gconf: cleanup rules used by dropped gconf2 package

---

profiles/easy
profiles/restrictive
profiles/standard

org.freedesktop.timesync1.set-runtime-servers
org.freedesktop.hostname1.get-hardware-serial
org.freedesktop.hostname1.get-description
https://bugzilla.suse.com/show_bug.cgi?id=1200098

Whitelist new systemd methods (bsc#1200098)

---

profiles/easy
profiles/restrictive
profiles/standard

Hardening the authentication requirements for restrictive probably will
easily raise hell since authentication popups on login, maybe even
multiple ones would be the result. Therefore keep the upstream setting
everywhere.

iio-sensor-proxy (bsc#1201558): add claim-sensor action

---

profiles/easy

Similar to #84, the user is prompted for admin password for simple stuff like changing hostname, setting locale and keyboard layouts
This patch sets the policy to match other distro's setup
Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

 Fix Settings prompts on desktop

---

profiles/easy

When using NetworkManager, the user is prompted for admin password for simple stuff like using WiFi, changing eth adapter, IPs and so on
This patch sets the policy to match other distro's setup
Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

Fix NetworkManager prompts on desktop

---

profiles/easy
profiles/restrictive
profiles/standard

https://bugzilla.suse.com/show_bug.cgi?id=1211978#c4

Whitelist org.freedesktop.systemd1.bypass-dump-ratelimit (bsc#1211978).

---

profiles/easy
profiles/restrictive
profiles/standard

Our deepin maintainer has difficulties bringing the new version into Factory, thus we need both names for the moment.

deepin-api: provide backward compatibility whitelisting (bsc#1214101)

---

profiles/easy
profiles/restrictive
profiles/standard

This has been removed upstream in commit db1a9c4af:
https://github.com/PackageKit/PackageKit/commit/db1a9c4af758fbe62d297f5516a46085cbd84f54)
https://github.com/PackageKit/PackageKit/issues/567
The Factory package no longer contains this.

profiles: remove no longer used device-rebind action

---

profiles/easy
profiles/restrictive
profiles/standard

The service was renamed from `net.hadess.PowerProfiles`, however the old service is being kept to ensure backwards compatibility, for a while.
https://bugzilla.suse.com/show_bug.cgi?id=1219956
https://bugzilla.suse.com/show_bug.cgi?id=1219957

profiles: power-profiles-daemon (bsc#1219957)

---

profiles/polkit-default-privs.easy
profiles/polkit-default-privs.restrictive
profiles/polkit-default-privs.standard

The maintainer asked for a Leap 15.6 backport.
https://bugzilla.suse.com/show_bug.cgi?id=1232244

profiles: xfce4-power-manager (bsc#1232244)

---

profiles/easy
profiles/restrictive
profiles/standard

pkexec is required for the administrative user interface.
https://bugzilla.opensuse.org/show_bug.cgi?id=1234134

profiles: whitelist timekpr-next (bsc#1234134)

---

profiles/easy
profiles/restrictive
profiles/standard

There is a request to add this to Leap 16.0:
https://build.opensuse.org/request/show/1271698
Whitelisting needs to go to SLFO:Main for this.

profiles: whitelist kio-admin (bsc#1229913)
